// Profils de véhicules utilisés dans l'écran "Nouveau trajet" et "Mes véhicules"

export const VEHICLE_PROFILES = [
  {
    name: "Tesla Model 3",
    empty_mass: 1850,
    extra_load: 150,
    drag_coefficient: 0.58, // CdA (Cd × A)
    frontal_area: 2.2, // m²
    rolling_resistance: 0.008,
    motor_efficiency: 0.95,
    regen_efficiency: 0.85,
    aux_power_kw: 2.0,
    battery_kwh: 75,
    usable_battery_kwh: 70,
    nominal_voltage: 350,
    battery_age_years: 0,
    max_charge_kw: 250,
  },
  {
    name: "Tesla Model Y",
    empty_mass: 2000,
    extra_load: 150,
    drag_coefficient: 0.62,
    frontal_area: 2.4,
    rolling_resistance: 0.008,
    motor_efficiency: 0.95,
    regen_efficiency: 0.85,
    aux_power_kw: 2.2,
    battery_kwh: 75,
    usable_battery_kwh: 70,
    nominal_voltage: 400,
    battery_age_years: 0,
    max_charge_kw: 250,
  },
  {
    name: "Audi Q4 e-tron",
    empty_mass: 2100,
    extra_load: 150,
    drag_coefficient: 0.70,
    frontal_area: 2.5,
    rolling_resistance: 0.009,
    motor_efficiency: 0.92,
    regen_efficiency: 0.80,
    aux_power_kw: 2.5,
    battery_kwh: 82,
    usable_battery_kwh: 77,
    nominal_voltage: 400,
    battery_age_years: 0,
    max_charge_kw: 135,
  },
  {
    name: "BMW iX3",
    empty_mass: 2180,
    extra_load: 150,
    drag_coefficient: 0.68,
    frontal_area: 2.4,
    rolling_resistance: 0.009,
    motor_efficiency: 0.93,
    regen_efficiency: 0.82,
    aux_power_kw: 2.3,
    battery_kwh: 80,
    usable_battery_kwh: 74,
    nominal_voltage: 400,
    battery_age_years: 0,
    max_charge_kw: 155,
  },
  {
    name: "Mercedes EQC",
    empty_mass: 2425,
    extra_load: 150,
    drag_coefficient: 0.72,
    frontal_area: 2.5,
    rolling_resistance: 0.010,
    motor_efficiency: 0.91,
    regen_efficiency: 0.78,
    aux_power_kw: 2.8,
    battery_kwh: 80,
    usable_battery_kwh: 76,
    nominal_voltage: 400,
    battery_age_years: 0,
    max_charge_kw: 110,
  },
  {
    name: "Volkswagen ID.4",
    empty_mass: 2120,
    extra_load: 150,
    drag_coefficient: 0.66,
    frontal_area: 2.3,
    rolling_resistance: 0.009,
    motor_efficiency: 0.90,
    regen_efficiency: 0.75,
    aux_power_kw: 2.0,
    battery_kwh: 77,
    usable_battery_kwh: 72,
    nominal_voltage: 350,
    battery_age_years: 0,
    max_charge_kw: 125,
  },
  {
    name: "Renault Zoe",
    empty_mass: 1500,
    extra_load: 150,
    drag_coefficient: 0.65,
    frontal_area: 1.9,
    rolling_resistance: 0.010,
    motor_efficiency: 0.90,
    regen_efficiency: 0.70,
    aux_power_kw: 1.5,
    battery_kwh: 52,
    usable_battery_kwh: 48,
    nominal_voltage: 400,
    battery_age_years: 0,
    max_charge_kw: 50,
  },
  {
    name: "BMW i3",
    empty_mass: 1200,
    extra_load: 150,
    drag_coefficient: 0.50,
    frontal_area: 1.8,
    rolling_resistance: 0.008,
    motor_efficiency: 0.92,
    regen_efficiency: 0.80,
    aux_power_kw: 1.8,
    battery_kwh: 42,
    usable_battery_kwh: 38,
    nominal_voltage: 360,
    battery_age_years: 0,
    max_charge_kw: 50,
  },
  {
    name: "Nissan Leaf",
    empty_mass: 1600,
    extra_load: 150,
    drag_coefficient: 0.68,
    frontal_area: 2.1,
    rolling_resistance: 0.010,
    motor_efficiency: 0.88,
    regen_efficiency: 0.75,
    aux_power_kw: 1.7,
    battery_kwh: 40,
    usable_battery_kwh: 36,
    nominal_voltage: 360,
    battery_age_years: 0,
    max_charge_kw: 50,
  },
  {
    name: "Hyundai IONIQ 5",
    empty_mass: 1950,
    extra_load: 150,
    drag_coefficient: 0.64,
    frontal_area: 2.3,
    rolling_resistance: 0.008,
    motor_efficiency: 0.94,
    regen_efficiency: 0.83,
    aux_power_kw: 2.1,
    battery_kwh: 73,
    usable_battery_kwh: 68,
    nominal_voltage: 650,
    battery_age_years: 0,
    max_charge_kw: 230,
  },
  {
    name: "Kia EV6",
    empty_mass: 1980,
    extra_load: 150,
    drag_coefficient: 0.63,
    frontal_area: 2.3,
    rolling_resistance: 0.008,
    motor_efficiency: 0.94,
    regen_efficiency: 0.83,
    aux_power_kw: 2.1,
    battery_kwh: 77,
    usable_battery_kwh: 72,
    nominal_voltage: 650,
    battery_age_years: 0,
    max_charge_kw: 230,
  },
  {
    name: "Custom",
    empty_mass: 1900,
    extra_load: 150,
    drag_coefficient: 0.62,
    frontal_area: 2.2,
    rolling_resistance: 0.010,
    motor_efficiency: 0.90,
    regen_efficiency: 0.60,
    aux_power_kw: 2.0,
    battery_kwh: 60,
    usable_battery_kwh: 55,
    nominal_voltage: 400,
    battery_age_years: 0,
    max_charge_kw: 150,
  },
];



